# Site settings
title: shaoyuan1943
email: shao_yuan1943@qq.com
description: shaoyuan的博客 C++\Lua Dev
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  shaoyuan1943
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false

# gitment
gitment:
  enable: true
  githubID: shaoyuan1943
  repo: http://shaoyuan1943.github.io/
  ClientID: "70812db7a48ce6d4e728"
  ClientSecret: "a38a3c54bb3957c0bf74bd52e9fba2e91e938bb8"
  lazy: true